version: "3"
services:

  # Frontend
  react-app:
    image: react-app
    build: ./client/
    stdin_open: true # Don't exit the developer server
    ports:
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules # Add a mount to the node_modules

  # Backend
  api-server:
    image: api-server
    build: ./server/
    ports:
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules # Add a mount to the node_modules
    depends_on:
      - mongo

  # Database
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db # Default path where mongo stores its data

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local